spring:
  config:
    activate:
      on-profile: local
    import:
      classpath:/application-aws.yml
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/bonheur
    username: bonheur
    password: bo123

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        show_sql: true
---
spring:
  profiles:
    active: dev